### Importando a biblioteca Numpy

* Numpy é mais adequado para dados homogêneos

In [1]:
import numpy as np

### Gerar um NDArray de 2x3 (matriz 2x3, 2 linhas e 3 colunas)

In [2]:
dados = np.random.rand(2,3)
print(dados)

[[0.63100341 0.06010908 0.1344365 ]
 [0.46599241 0.33649442 0.59220247]]


### Mostrar o tipo de array que foi gerado

In [3]:
print(dados.dtype)

float64


### Ver tamanho e quantidade de dimensões

In [5]:
# mostra o tamanho da matriz
print(dados.shape)

# mostra o número de dimensões da matriz
print(dados.ndim)

(2, 3)
2


### np.array cria um array np a partir de uma lista 

In [6]:
lista = [1,2,3,4,5.5,6.7]

dados2 = np.array(lista)

print(dados2)

[1.  2.  3.  4.  5.5 6.7]


In [8]:
lista2 = [[1,2,3,4], [4,3,2,1]]

dados3 = np.array(lista2)

print(dados3)
print(dados3.shape, dados3.ndim)

[[1 2 3 4]
 [4 3 2 1]]
(2, 4) 2


### Outras maneiras de criar arrays

In [9]:
# cria um array de n posições preenchidas por 0s
dadosZeros = np.zeros(10)

print(dadosZeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
# cria uma matriz de dimensões n x m, preenchidas por 0
dadosZeros2 = np.zeros((2,3))

print(dadosZeros2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# cria um array de n posições preenchidas por 1s
dadosUm = np.ones(10)

print(dadosUm)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# cria uma matriz de dimensões n x m, preenchidas por 1
dadosUm1 = np.ones((2,2))

print(dadosUm1)

[[1. 1.]
 [1. 1.]]


In [14]:
# Cria um array de n valores sequenciais
dadosSeq = np.arange(10)

print(dadosSeq)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# cria um array que vai de 0 até 20, indo de 2 em 2
dadosSeq2 = np.arange(0,20,2)

print(dadosSeq2)

[ 0  2  4  6  8 10 12 14 16 18]


### Também é possível transformar os tipo dos dados

In [17]:
# Converte os dados para tipo float64
dadosSeqf = dadosSeq2.astype(np.float64)

print(dadosSeqf.dtype)

float64


## Aritmética com Arrays

In [ ]:
dados4 = np.array([[1,2,3], [4,5,6]])

print(dados4)

# pode-se fazer soma,subtração, multiplicação, tudo utilizando os arrays

[[1 2 3]
 [4 5 6]]


### Slicing

In [25]:
print(dadosSeq[2:5])

dadosSeq[2:5] = 20
print(dadosSeq)

fatiaDados = dadosSeq[2:4]
print(fatiaDados)

[20 20 20]
[ 0  1 20 20 20  5  6  7  8  9]
[20 20]


### Criando cópia dos dados

In [ ]:
# Ao gerar uma cópia e alterar a cópia, não altera o original, apenas a cópia
fatia2 = dadosSeq[2:4].copy()
fatia2[:] = 99

print(fatia2)
print(dadosSeq)

[99 99]
[ 0  1 20 20 20  5  6  7  8  9]


### Array com mais de uma dimensão

In [ ]:
dados6 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(dados6)

# funciona como matriz
print(dados6[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


### Máscaras

In [ ]:
# Faz uma comparação para cada elemento do array e guarda na mascara
mascara = (dadosSeq < 50)
print(mascara)

[ True  True  True  True  True  True  True  True  True  True]


In [ ]:
# Atribue todos os elementos que são menores do que 20 o valor de 8888 
# Usa a máscara para fazer essa comparação, atribuindo o valorsomente aqueles que são True
dadosSeq[dadosSeq<20] = 8888

print(dadosSeq)

[8888 8888   20   20   20 8888 8888 8888 8888 8888]


### Transposição

In [ ]:
# Cria um array de 15 elementos e o configura para dimensão de 3x5 (3 linhas e 5 colunas)
dados7 = np.arange(15).reshape((3,5))

print(dados7)

# Transpoe a matriz
print(dados7.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Multiplicação de Matrizes

In [32]:
print(np.dot(dados7, dados7.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
