In [2]:
import numpy as np
import sys

#### Básico

In [3]:
# Cria vetores numpy, np.array, pode definir o tipo dos elementos
a = np.array([1,2,3], dtype='int8')
b = np.array([[1.0,2.0,3.0], [2.2,3.3,4.4]])

print(b)

[[1.  2.  3. ]
 [2.2 3.3 4.4]]


In [4]:
# Retornar dimensão, usando x.ndim
print(a.ndim)

print(b.ndim)

1
2


In [5]:
# Retorna o formato, linhas x colunas
b.shape

(2, 3)

In [6]:
# Retornar tipo
a.dtype

dtype('int8')

In [7]:
# Retorna o tamanho de cada item em bytes
a.itemsize

1

In [8]:
# Retorna o tamanho total em bytes 
b.nbytes

48

#### Acessando / Modificando items específicos, colunas, linhas, etc.

In [9]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
a.shape

(2, 7)

In [11]:
# Retornar um elemento específico [r, c] [linha, coluna] ( como em uma matriz normal )
a[1, 5]

np.int64(13)

In [12]:
# Retornar uma linha específica
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Retornar uma coluna específica
a[:, 3]

array([ 4, 11])

In [18]:
# Complicando um pouco mais [inicio:fim:step]
# Pode ser usado tanto para linha quanto para coluna
# Nesse caso, primeiro ele seleciona que quer a linha 0
# Na parte das colunas, marca que começa da coluna de índice 1 e vai até a coluna de índice 5 (6 -1) com step de 2, pulando de 2 em 2
a[0, 1:-1:2]

array([2, 4, 6])

In [19]:
# Para alterar elementos, basta fazer atribuições diretas
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [21]:
# Essa alteração pode ser efeituada para uma linha ou coluna inteira
a[:, 2] = [-1,-1]
a

array([[ 1,  2, -1,  4,  5,  6,  7],
       [ 8,  9, -1, 11, 12, 20, 14]])

Exemplo em 3D

In [26]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
# Retornando um elemento específico de um array 3d
# Primeiro escolha qual dos blococ quer, dos mostrados acima, há 2 blocos (1,2,3,4 e 5,6,7,8)
# Depois escolha a linha e a coluna do bloco escolhido
b[1,1,1]

np.int64(8)

In [29]:
# Pega a segunda linha inteira de todos os blocos
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [33]:
# Substituir em array 3d, é preciso criar uma subsequencia da mesma dimensao !!!!
b[:,1,:] = [[6,6], [6,6]]

b

array([[[1, 2],
        [6, 6]],

       [[5, 6],
        [6, 6]]])

#### Inicializando diferentes tipos de Array

In [37]:
# Matriz com apenas 0s
# É necessário apenas passar as dimensões como parâmetro da função
a = np.zeros((2,2,3))

a

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
# Matriz com apenas 1s
# Precisa passar as dimensões
# Também é possível especificar o tipo de dado na matriz
a = np.ones((2,2,2,2), dtype='int32')

a

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]], dtype=int32)

In [41]:
# Qualquer outro número
# Recebe dois parâmetros, primeiro a dimensão do array e depois o valor com que ele será preenchido
a = np.full((2,2), 99, dtype='int8')

a

array([[99, 99],
       [99, 99]], dtype=int8)

In [42]:
# Qualquer outro número
# Recebe como parâmetro um array e um valor
# Assim, ele cria um novo array com a dimensão do array passado, porém preenchido com o valor passado
np.full_like(a, 4)


array([[4, 4],
       [4, 4]], dtype=int8)

In [45]:
# Inicializar uma matriz com números decimais aleatórios
# Gera uma matriz de valores decimais aleatória com as dimensões passadas
np.random.rand(2,2,2)

array([[[0.88059264, 0.50878915],
        [0.52015806, 0.52756659]],

       [[0.86295864, 0.59242649],
        [0.41535014, 0.47435962]]])

In [50]:
# Valores inteiros aleatórios
# O primeiro parâmetro recebe o valor de inicio e o ultimo de fim
# Já o segundo parâmetro, size, recebe as dimensões
np.random.randint(-2,6, size=(2,4))

array([[ 3,  5,  1, -1],
       [ 1,  1, -1,  4]], dtype=int32)

In [51]:
# A matriz de identidade
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
arr = np.array([[1,2,3]])

# np.repeat repete o determinado array em n vezes, no eixo passado como parametro
# neste caso, o eixo é de linha
# se fosse coluna, ia repetir cada uma das colunas 3 vezes 
r1 = np.repeat(arr,3, axis=0)

r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [62]:
# Pequeno ex
a = np.ones((5,5), dtype=int)

b = np.zeros((3,3))

b[1,1] = 9

# No slicing, pode fazer atribuição de varios elementos de uma só vez, incluindo diversas linhas e colunas
a[1:4, 1:4] = b

a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### <strong>Cuidado ao copiar arrays!!!</strong>

In [63]:
a = np.array([1,2,3])

b = a

# O endereço de memório é o mesmo, assim b e a funcionam apenas como ponteiros
# Atribuir um array diretamente apenas copia o endereço de memória, podendo afetar o array original
b[0] = 100

a

array([100,   2,   3])

Para copiar um array para outra variável de maneira correta, deve-se usar o método .copy()

In [65]:
a = np.array([1, 2, 3])

# Somente ao usar o método .copy() é que o array será verdadeiramente copiado, não só o endereço de memória
b = a.copy()

b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


#### Matemática

possibilita adições, subtrações, multiplicações, etc. Tudo sobre o array

In [67]:
a = np.array([1,2,3,4])

a

array([1, 2, 3, 4])

In [68]:
a + 2

array([3, 4, 5, 6])

In [69]:
a - 2

array([-1,  0,  1,  2])

In [70]:
a * 2

array([2, 4, 6, 8])

In [73]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [74]:
b = np.array([1,0,1,0])

In [76]:
a + b

array([2, 2, 4, 4])

In [77]:
a ** 2

array([ 1,  4,  9, 16])

In [78]:
# Calcula o seno dos valores
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [79]:
# Calcula o coseno
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Algebra Linear

Numpy suporta diversas operações de algebra linear, o que facilita muito o tratamento de dados.

In [82]:
a = np.full((2,3), 1)

a

array([[1, 1, 1],
       [1, 1, 1]])

In [84]:
b = np.full((3,2), 2)

b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [85]:
# Realiza operações de algebra linear entre matrizes
np.dot(a,b)

array([[6, 6],
       [6, 6]])

In [137]:
c = np.identity(3)

# Acha o determinante de uma matriz
np.linalg.det(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Estatísticas

##### <strong>em numpy, axis = 0 refere-se as colunas, já axis = 1 refere-se as linhas</strong>

In [107]:
stats = np.array([[1,2,3], [4,5,6]])

# Encontra o menor elemento da array
# Pode-se aplicar o eixo também, em linhas ou colunas
# Ao se aplicar para linha, retorna o menor elemento de cada linha, o mesmo vale para colunas
stats.min(axis=1)

array([1, 4])

In [96]:
# Retorna o maior elemento
stats.max(axis=0)

array([4, 5, 6])

In [104]:
# Retorna o somatório de toda a array
# Pode-se aplicar para um eixo específico, axis = 0 retorna o somatório de cada coluna, axis = 1 retorna o somatório de cada linha
stats.sum(axis=1)

array([ 6, 15])

#### Reorganizando arrays

In [111]:
before = np.array([[1,2,3,4], [5,6,7,8]])

before.shape

(2, 4)

In [115]:
# Ao reorganizar arrays, podemos alterar suas dimensões, de 2x4 pode ir para 8x1
# Deve manter a qtd de elementos original, fora isso pode fazer qualquer alteração
# Para isso usa-se o metodo reshape, a partir do array original
# Recebe como parametro as novas dimensoes
after = before.reshape((8,1))

print(after)

after = before.reshape((2,2,2))

print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [117]:
# Empilhando matrizes verticalmente, a primeira fica no topo, a segunda embaixo e por ai vai
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

np.vstack([v1,v2,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [118]:
# Mesmo processo, só que horizontal, praticamente uma concatenação
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

np.hstack([v1,v2,v2])

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

#### Outras coisas

Carregando data de um arquivo

In [122]:
# A função np.genfromtxt() faz a leitura de um arquivo e separa os dados com base em um delimitador
# No caso do exemplo, o delimitador entre dados do arquivo é uma vírgula ,
data = np.genfromtxt('data.txt', delimiter=',')

# Além disso, é possível converter o tipo dos dados para outro
# usa-se o método .astype(tipo)
data = data.astype("int32")

data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

#### Máscaras booleanas e indexação avançada

In [ ]:
# Cria um array de valores booleanos
# Sendo True os índices nos valores onde a condição é verdadeira e False onde não é
mask = data > 50

In [127]:
# Ao usar a máscara como índice, apenas os valores com índice igual a True serão printados
data[mask]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [133]:
# Outra opção é fazer direto, sem o uso da máscara como auxiliar
data[(data > 50)]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [129]:
# é possível indexar com uma lista em Numpy
a = np.array([1,2,3,4,5,6,7,8,9])

# Passa indíces como índice de a, retornando aqueles valores que correspondem aos indices passados
# Vantajoso pois pode-se acessar mais de um índice de uma única vez
a[[1,2,8]]

array([2, 3, 9])

In [130]:
# np.any recebe uma condição e um eixo
# retorna os indices como True daqueles que cumprem aquela condição no dado eixo
np.any(data > 5, axis= 0)

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True])

In [131]:
# Pode-se aplicar mais de uma condição sob a máscara
((data > 50) & (data < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

<strong>Um simbolo lógico muito útil em Numpy é o ~, que corresponde à negação</strong>

In [135]:
# Exemplo da negação
mask = data > 50

# A negação (~) inverte todos os valores booleanos
print(mask)
mask_neg = ~mask

print(mask_neg)

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[[ True  True  True  True False False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True False False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True False  True  True  True False  True  True  True
   True  True  True  True False False]]


In [ ]:
# Repostas do ex do video

# Pergunta 1
a[2:4, 0:2]

# Pergunta 2
a[[0,1,2,3], [1,2,3,4]]

# Pergunta 3
a[[0,-2,-1], 3:]
